DATABASE_URL: ENC[AES256_GCM,data:4GHNcZxF54G+TU5QVIZB/V3bn0bXqisKccQ35TJNHKTc,iv:2OaA27AIMPUM4HxhFSlIe+3Yv6iWoawCv4tQFNWZf3E=,tag:5NlkF3wmyLT8KheMgnIy9g==,type:str]
JWT_SECRET: ENC[AES256_GCM,data:VBfZrAY=,iv:ZNoJ6Re6xd1rfnLCAp2l9KwsoisSI0G21vi4DLJs92Y=,tag:8wgbJYqX4dAqGA0sPxn2Dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOERxQXlDMGp6Rm81ZENl
            YzlvS2o0NjdKNmZwVWxCOFQ5a1RMWVl6UWp3Cmh1RktrdEY3dGk1WHBEUDMrWGN4
            VFl0WlJMVmYxS01uUXFMRmFkaHNRSFUKLS0tIGRZenFtVjdoU0tnUFk3MU94L1Zo
            TUo2VENVTnpIcWRCWmxuMmxZcG82bEEKfn8QARLq+iPHTMjNHK0XPTsc2g1NZs/q
            R6gIymWj8iYF5M+sn7QqtcPuTb0bOcaqetp8e23MPQdnqki/fZju4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gvan8zw33ujvalzhvahkg7kapwk08yynmmlfn5dsss6zud7ez4pqcz9fx3
    lastmodified: "2026-07-01T12:50:46Z"
    mac: ENC[AES256_GCM,data:dGVwyjAPAQGSMpHAskR2ihSBurXtoVcGJUzZ/80E4Us4tTzYFq6AjVr61KA1bcFMbpLVYXUt2uHdbZkvfO6i7MR60H43swW5Rm3xSbGJQ3BChHNeSM62CSEhNJpJWEa+P7uwtFKl1cssWc+/PshwnOaPIA+E4F9TY/xnRB8O0/I=,iv:BAlxC64hL4axXictegQaLHqXSNEpyJhyywDF6916imI=,tag:gJsUdW2xU3W1vV2SoX2Z+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
